print('Please enter the following')
print()
#Request basic information given for this story
adj = input('Adjective:')
anImal = input('Animal:')
verb1 = input('Verb:')
exC = input('Exclamation:')
verb2 = input('Verb:')
verb3 = input('Verb:')
#Request more information for creativity(additional task)
exC2 = input('Exclamation:')
verb4 = input('Verb:')
print()
print('Your story is: ')
print()
print(f'The other day, I was really in trouble. It all started when I saw a very \n{adj} {anImal} {verb1} down the hallway. "{exC.capitalize()}!" I yelled. But all \nI could think to do was to {verb2} over and over. Miraculously, \nthat caused it to stop, but not before it tried to {verb3} \nright in front of my family.')
#Additional sentence for the story(additional task)
print()
print(f'"{exC2.capitalize()}!" I exclaimed, my daugther does not like {anImal},\nI wished I had {verb4} my family earlier, my daughter would not have seen it.')